"""add_flow_info

Revision ID: f67e797dcd00
Revises: 
Create Date: 2025-02-17 14:03:46.704259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f67e797dcd00'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FLOW_INFO',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src_ip', sa.Text(), nullable=False),
    sa.Column('dst_ip', sa.Text(), nullable=False),
    sa.Column('src_port', sa.Integer(), nullable=False),
    sa.Column('dst_port', sa.Integer(), nullable=False),
    sa.Column('ipv', sa.Integer(), nullable=False),
    sa.Column('tcp_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('proto', sa.String(length=50), nullable=False),
    sa.Column('src_country', sa.String(length=100), nullable=True),
    sa.Column('dst_country', sa.String(length=100), nullable=True),
    sa.Column('src_as', sa.Integer(), nullable=True),
    sa.Column('dst_as', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.BigInteger(), nullable=False),
    sa.Column('last_seen', sa.BigInteger(), nullable=False),
    sa.Column('num_pkts', sa.BigInteger(), nullable=False),
    sa.Column('len_pkts', sa.BigInteger(), nullable=False),
    sa.Column('ndpi', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FLOW_INFO')
    # ### end Alembic commands ###
