name: Check C sources
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  release:
    types: [created]
jobs:
  sast:
    name: SAST (ubuntu latest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install nDPI prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install autoconf automake libtool pkg-config gettext flex bison libjson-c-dev libpcap-dev rrdtool librrd-dev parallel libpcre3-dev libmaxminddb-dev
      - name: Prepare build
        run: |
          mkdir build && cd build
          cmake .. -DDEBUG=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=OFF
      - name: CodeChecker
        uses: whisperity/codechecker-analysis-action@v1
        id: codechecker
        with:
          build-command: "cd ${{ github.workspace }}/Build; cmake --build ."
      - name: Deploy SAST artfs
        uses: actions/upload-artifact@v2
        with:
          name: "CodeChecker Bug Reports"
          path: ${{ steps.codechecker.outputs.result-html-dir }}

    # Break the build if there are *ANY* warnings emitted by the analysers.
      - name: Break build if CodeChecker reported any findings
        if: ${{ steps.codechecker.outputs.warnings == 'true' }}
        run: exit 1