name: Check golang sources
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  release:
    types: [created]
jobs:
  sast:
    name: SAST (ubuntu latest)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.2
      - name: Install Prerequisites
        run: |
            sudo apt-get update
            sudo apt-get install libzmq3-dev
      - name: lint
        uses: golangci/golangci-lint-action@v6.5.0
        with:
          version: latest
          working-directory: ./collector