name: Check OpenAPI spec
on:
  push:
    paths:
      - 'api/schema/**'
      - '.github/workflows/openapi.yaml'
    branches:
      - main

  pull_request:
    paths:
      - 'api/schema/**'
      - '.github/workflows/openapi.yaml'
    branches:
      - main
    types: [opened, synchronize, reopened]

  release:
    types: [created]

jobs:
  docs:
    name: Lint, build and attach docs 
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read
      checks: write
      issues: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version-file: 'ui/.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'ui/package-lock.json'

      - name: Install deps
        run: npm ci
        working-directory: ui

      - name: lint docs
        id: lint_docs
        run: npm run test:api-docs
        working-directory: ui

      - name: build docs
        id: build_docs
        run: npm run build:api-docs
        working-directory: ui

      - name: Upload static open api html
        uses: actions/upload-artifact@v4
        with:
          name: openapi.html
          path: api/schema/openapi.html
