name: Check frontend sources
on:
  push:
    paths:
      - 'ui/**'
      - '.github/workflows/ui.yaml'
    branches:
      - main

  pull_request:
    paths:
      - 'ui/**'
      - '.github/workflows/ui.yaml'
    branches:
      - main
    types: [opened, synchronize, reopened]

  release:
    types: [created]

jobs:
  run-ui-submit:
    name: Build project (with sast)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ui

    permissions:
      contents: read
      pull-requests: read
      checks: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: npm ci

      - name: Run submit script and capture output
        id: run_submit
        run: |
          echo "Running npm run submit..."
          npm run submit
