name: Check frontend sources
on:
  push:
    paths:
      - 'ui/**'
      - '.github/workflows/ui.yaml'
    branches:
      - main

  pull_request:
    paths:
      - 'ui/**'
      - '.github/workflows/ui.yaml'
    branches:
      - main
    types: [opened, synchronize, reopened]

  release:
    types: [created]

jobs:
  run-ui-submit:
    name: Build project (with sast)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ui

    permissions:
      contents: read
      pull-requests: read
      checks: write
      issues: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version-file: 'ui/.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'ui/package-lock.json'

      - name: Install deps
        run: npm ci

      - name: CodeQL init
        uses: github/codeql-action/init@v3
        with:
          config-file: .github/codeql/frontend-config.yaml

      - name: CodeQL analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: '/language:javascript'

      - name: Run submit script and capture output
        id: run_submit
        run: |
          echo "Running npm run submit..."
          npm run submit
